"""GitHub Actions workflow generator for ``osspulse schedule --github-actions``.

Pure module — no I/O, no subprocess.  Generates a valid Actions YAML string
with:
  - ``on.schedule.cron`` set to the given expression
  - A comment noting that Actions schedule.cron is evaluated in UTC (AC-V2-002-017)
  - ``${{ secrets.GITHUB_TOKEN }}`` and ``${{ secrets.LLM_API_KEY }}`` refs
    (secretless artifact, AC-V2-002-015, BR-V2-002-001)

Design: the generator builds the YAML as a plain string (no YAML library needed
for this simple template; avoids a new dependency per lean-stack principle).
"""

from __future__ import annotations

from osspulse.schedule.errors import ScheduleError

# Template for the generated GitHub Actions workflow.
# Placeholders: {cron_expr}
_WORKFLOW_TEMPLATE = """\
# Generated by osspulse schedule --github-actions
# NOTE: GitHub Actions schedule.cron expressions are evaluated in UTC.
#       Your OS cron runs in the system local timezone — they may diverge.
name: osspulse-run

on:
  schedule:
    # UTC timezone (AC-V2-002-017)
    - cron: "{cron_expr}"
  workflow_dispatch:  # allow manual trigger

jobs:
  osspulse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install osspulse
        run: pip install osspulse

      - name: Run osspulse
        env:
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
          LLM_API_KEY: ${{{{ secrets.LLM_API_KEY }}}}
        run: osspulse run --config config.toml
"""


def generate_workflow(cron_expr: str) -> str:
    """Generate a GitHub Actions workflow YAML for the given cron expression.

    The output:
    - Sets ``on.schedule.cron`` to *cron_expr*
    - Includes a UTC-timezone comment (AC-V2-002-017)
    - References ``${{ secrets.GITHUB_TOKEN }}`` and ``${{ secrets.LLM_API_KEY }}``
      (never inlining secret values — AC-V2-002-015, BR-V2-002-001)

    Args:
        cron_expr: a validated 5-field cron expression.

    Returns:
        A multi-line YAML string (trailing newline included).

    Raises:
        ScheduleError: if *cron_expr* contains characters that would break the YAML
            (defensive check; callers should pre-validate with ``validate_cron_expr``).
    """
    # Defensive: reject double-quote in the expression (would break YAML string)
    if '"' in cron_expr:
        raise ScheduleError(
            f"cron expression {cron_expr!r} contains a double-quote character "
            "which is invalid in YAML"
        )
    return _WORKFLOW_TEMPLATE.format(cron_expr=cron_expr)
